function h = showSurfRegResults(headTmpl,dataSurf)
%

h = uifigure('Name','Head surface registration result',...
    'Tag','uifig_hsurfRegistResult');
ah = axes('Parent',h,'Units','normalized','Position',[0 0 1 1],...
    'Visible','off','NextPlot','add');
axis(ah,'vis3d','equal');
rotate3d(ah,'on');
view(ah,180,40);

lh = lightangle(ah, 120,30);
lh = lightangle(ah,-120,30);

ph_mdl = patch('Parent',       ah, ...
           'Faces',         headTmpl.faces, ...
           'Vertices',      headTmpl.vertices, ...
           'EdgeColor',     'none', ...
           'FaceColor',     [1 0.8 0.7], ...
           'FaceAlpha',     .4, ...
           'FaceLighting',  'gouraud');
material(ph_mdl,'dull');

ph_data = patch('Parent',       ah, ...
           'Faces',         dataSurf.faces, ...
           'Vertices',      dataSurf.vertices, ...
           'EdgeColor',     'k', ...
           'EdgeAlpha',     1, ...
           'FaceColor',     'none', ...
           'Marker',        '.', ...
           'MarkerEdgeColor','b');

xyzMin = min(headTmpl.vertices);
xyzMax = max(headTmpl.vertices);
xyzMin = xyzMin - abs(xyzMax-xyzMin)*.05;
xyzMax = xyzMax + abs(xyzMax-xyzMin)*.05;

col = hsv(3);
lh = plot3(ah, [xyzMin(1) xyzMax(1)],   [0 0],   [0 0],...
    'Marker',       'none',         'MarkerFaceColor',     col(1,:),...
    'Color',        col(1,:));
lh = plot3(ah, [0 0],   [xyzMin(2) xyzMax(2)],   [0 0],...
    'Marker',       'none',         'MarkerFaceColor',     col(2,:),...
    'Color',        col(2,:));
lh = plot3(ah, [0 0],   [0 0],   [xyzMin(3) xyzMax(3)], ...
    'Marker',       'none',         'MarkerFaceColor',     col(3,:),...
    'Color',        col(3,:));

xyzMin = xyzMin - abs(xyzMax-xyzMin)*.07;
xyzMax = xyzMax + abs(xyzMax-xyzMin)*.07;

text(ah, xyzMin(1), 0, 0, 'X<0', 'HorizontalAlignment','right', 'FontWeight','bold');
text(ah, xyzMax(1), 0, 0, 'X>0', 'HorizontalAlignment','left',  'FontWeight','bold');
text(ah, 0, xyzMin(2), 0, 'Y<0', 'HorizontalAlignment','right', 'FontWeight','bold');
text(ah, 0, xyzMax(2), 0, 'Y>0', 'HorizontalAlignment','left',  'FontWeight','bold');
text(ah, 0, 0, xyzMin(3), 'Z<0', 'HorizontalAlignment','center','FontWeight','bold');
text(ah, 0, 0, xyzMax(3), 'Z>0', 'HorizontalAlignment','center','FontWeight','bold');
end